name: Staging Pipe

on:
  push:
    branches:
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: yarn
    - name: Build
      env:
        VUE_APP_A55_EBOX_API_KEY: ${{ secrets.VUE_APP_A55_EBOX_API_KEY }}
      run: yarn build:stage
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: yarn deploy:stage
